In [1]:
import numpy as np

In [120]:
pauli_x=np.array([[0,1],
                  [1,0]])
pauli_y=np.array([[0,1j],
                  [-1j,0]])
pauli_z=np.array([[1,0],
                  [0,-1]])
identidad=np.array([[1,0],
                    [0,1]])

def productodirecto(mat):
    resultado = mat[0]
    for k in mat[1:]:
        resultado = np.kron(resultado, k)
    return resultado
    

def Hamiltoniano_Ising(J,G,N):
    Hamiltoniano=np.zeros((2**N,2**N))

    for i in range(N-1):
        mat = [identidad for j in range(N)]
        mat[i] = pauli_z
        mat[(i + 1)] = pauli_z
        Hamiltoniano -= J * productodirecto(mat)

    for i in range(N):
        mat = [identidad for j in range(N)]
        mat[i] = pauli_x
        Hamiltoniano -= G * productodirecto(mat)
    
    return Hamiltoniano


N=10
J=1.0
G=1.0
H=Hamiltoniano_Ising(J,G,N)
print(H)

[[-9. -1. -1. ...  0.  0.  0.]
 [-1. -7.  0. ...  0.  0.  0.]
 [-1.  0. -5. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -5.  0. -1.]
 [ 0.  0.  0. ...  0. -7. -1.]
 [ 0.  0.  0. ... -1. -1. -9.]]


In [118]:
N=2
H=Hamiltoniano_Ising(J,G,N)
print(H)


[[-1. -1. -1.  0.]
 [-1.  1.  0. -1.]
 [-1.  0.  1. -1.]
 [ 0. -1. -1. -1.]]


In [ ]:
R=np.kron(pauli_z,pauli_z)
A=np.kron(pauli_x,identidad)
C=np.kron(identidad,pauli_x)
print((-R)-(A+C))